### ISSUE TITLE
Cannot bind to specific port: http://localhost:9191 - undertow

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-swarm/wildfly-swarm-camel#51] opened 2016-06-30 08:21 UTC
When a Camel route is started using the undertow component configured with a port number, then this error is generated

Code : https://github.com/cmoulliard/swarm-camel-demo/blob/master/src/main/java/org/demo/route/RestService.java

Version of Swarm used : 1.0.0.Final
Versions of Camel packaged :  

camel-core-1.1.0.jar
camel-core-2.17.1.jar
camel-spring-2.17.1.jar
camel-undertow-1.1.0.jar
camel-undertow-2.17.0.jar

```
2016-06-30 10:03:52,740 ERROR [stderr] (main) Caused by: java.lang.IllegalStateException: Cannot bind to specific port: http://localhost:9191/api/say
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.jboss.gravia.utils.IllegalStateAssertion.assertTrue(IllegalStateAssertion.java:59)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.wildfly.extension.camel.undertow.CamelUndertowHostService$WildFlyUndertowHost.validateEndpointURI(CamelUndertowHostService.java:177)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.apache.camel.component.undertow.UndertowConsumer.doStart(UndertowConsumer.java:72)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.wildfly.extension.camel.undertow.WildFlyUndertowComponent$WildFlyUndertowUndertowConsumer.doStart(WildFlyUndertowComponent.java:91)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3269)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRouteConsumers(DefaultCamelContext.java:3563)
2016-06-30 10:03:52,740 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.doStartRouteConsumers(DefaultCamelContext.java:3499)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3429)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3197)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3053)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:175)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2848)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:2844)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2867)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:2844)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
2016-06-30 10:03:52,741 ERROR [stderr] (main)   at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2813)
2016-06-30 10:03:52,742 ERROR [stderr] (main)   at org.wildfly.swarm.camel.core.runtime.CamelCoreConfiguration$BootstrapCamelContextService.start(CamelCoreConfiguration.java:131)

```

**Comment by jamesnetherton** [comment] 2016-06-30 09:01
This is intentional. 

The way that camel-undertow presently works on WildFly, is that it'll reuse the underlying undertow HTTP engine. So the port becomes irrelevant, as it'll be fixed by whatever port WildFly is configured to serve HTTP traffic on.

It should work fine if you omit the port entirely from the endpoint URI or use 8080. E.g:

```
from("undertow://http://localhost:8080/my/path")
```
```
from("undertow://http://localhost/my/path")
```

**Comment by cmoulliard** [comment] 2016-06-30 09:17
Do we have a documentation page about Camel running top of WildFly (Subsystem, Swarm, ...) to document such feature ?

**Comment by jamesnetherton** [comment] 2016-06-30 09:22
Yes here (see the last sentence):

https://wildflyext.gitbooks.io/wildfly-camel/content/components/camel-undertow.html

The doc should probably be improved to include specifics around port configuration.

**Comment by jamesnetherton** [comment] 2016-07-01 06:49
Closing this - I think the problem is explained.

Can repopen if not.

**Closed by jamesnetherton** 2016-07-01 06:49 UTC
